spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: 123
  redis:
    host: localhost   #redis主机地址
    port: 6379  #端口号
    jedis:
      pool:
        max-active: 18  #设置连接池最大连接数
        max-wait: 3000  #连接池最大阻塞等待时间
        max-idle: 20    #连接池中最大的空闲连接数
        min-idle: 2     #连接池中最小的空闲连接数
    connect-timeout: 3000 #连接超时时间

mybatis:
  configuration:
    map-underscore-to-camel-case: true      #    开启驼峰命名法
  mapper-locations: classpath:mapper/*.xml
